#!/bin/bash
#
# SPDX-License-Identifier: GPL-3.0-only
#
# Copyright (c) 2021, Antonio Niño Díaz

set -e

BASE_DIR=$(pwd)

# Build tools

pushd tools

rm -rf build ; mkdir build ; cd build
cmake ..
make

popd

# Paths to tools

export SUPERFAMICONV=../SuperFamiconv/bin/superfamiconv
export PNGS2STRIP=tools/build/pngs2strip/pngs2strip

# Prepare destination folder

OUT_DIR=built_assets
rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}

# Generate city tileset

bash maps/buildings/convert.sh maps/city

# Convert maps

OUT_DIR_MAPS_CITY=${OUT_DIR}/maps/city
mkdir -p ${OUT_DIR_MAPS_CITY}
bash maps/city/convert.sh ${OUT_DIR_MAPS_CITY}

OUT_DIR_MAPS=${OUT_DIR}/maps
mkdir -p ${OUT_DIR_MAPS}
bash maps/convert.sh ${OUT_DIR_MAPS}

OUT_DIR_MAPS_INTRO=${OUT_DIR}/maps/intro
mkdir -p ${OUT_DIR_MAPS_INTRO}
bash maps/intro/convert.sh ${OUT_DIR_MAPS_INTRO}

# Convert sprite sheets

mkdir ${OUT_DIR}/sprites

tools/build/png2sprites/png2sprites \
    ${OUT_DIR}/sprites/ \
    sprites/building_menu_tiles.png \
    sprites/building_menu_map.png

tools/build/png2sprites/png2sprites \
    ${OUT_DIR}/sprites/ \
    sprites/graph_menu_tiles.png \
    sprites/graph_menu_map.png

tools/build/png2sprites/png2sprites \
    ${OUT_DIR}/sprites/ \
    sprites/minimap_menu_tiles.png \
    sprites/minimap_menu_map.png

# Convert other graphics

mkdir ${OUT_DIR}/graphics

pushd ${OUT_DIR}/graphics
for png in $(find "${BASE_DIR}/graphics/" -name "*.png")
do
    echo grit ${png} -ftc -o $(basename ${png} ".png")
    grit ${png} -ftc -o $(basename ${png} ".png")
done
popd

# Convert music

mkdir ${OUT_DIR}/audio

../umod-player/build/packer/umod_packer \
    ${OUT_DIR}/audio/umod_pack.bin \
    ${OUT_DIR}/audio/umod_pack_info.h \
    audio/*

# Convert data files

# TODO

# Convert binary files generated by other stages

for dir in $(find built_assets -type d)
do
    for f in $(find $dir -maxdepth 1 -iname *.bin)
    do
        tools/build/bin2c/bin2c $f "$dir"
    done
done

# Done!

exit 0
